export const configs = {
  webUrl: process.env.webUrl,
  host: process.env.host,
  port: process.env.portDB || 3306,
  user: process.env.user,
  password: process.env.password,
  database: process.env.database,
  secret: process.env.secret,
  cert: process.env.CA_CERT,
  EMAIL_SERVER: process.env.EMAIL_SERVER,
  EMAIL_FROM: process.env.EMAIL_FROM,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  resend_api: process.env.resend_api,
  cloudinary_cloud_name: process.env.cloudinary_cloud_name,
  cloudinary_api_key: process.env.NEXT_PUBLIC_cloudinary_api_key,
  cloudinary_api_secret: process.env.cloudinary_api_secret,
  cloudinary_url: process.env.NEXT_PUBLIC_cloudinary_url,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXT_PUBLIC_BOOKING: process.env.NEXT_PUBLIC_BOOKING,
};
