name: Unread Alerts Scheduler

on:
  schedule:
    - cron: "*/5 * * * 1-5" # Every 5 minutes, Monday–Friday (UTC time)
  workflow_dispatch: # Manual trigger

jobs:
  send-unread-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request for Unread Alerts
        run: |
          curl "https://www.horizon-consultancy.com/api/unreadAlert" \
          -H "x-api-key: ${{ secrets.UNREAD_ALERTS_KEY }}" \
          --fail -v

      - name: Keep /pricing page warm
        run: |
          curl -s "https://www.horizon-consultancy.com/pricing" >/dev/null
